# target architecture - amd64, arm64 or all
ARCH="amd64"

# base codename
BASECODENAME="sid"

# base version
BASEVERSION="14"

# distribution codename - MaxregnerOS Revolutionary Edition
CODENAME="revolution"

# distribution version
VERSION="1.0"

# distribution channel
CHANNEL="stable"

# distribution name
NAME="MaxregnerOS"

# mirror to fetch packages from
MIRROR_URL="https://repo2.vanillaos.org"

# use HWE kernel and packages?
HWE="yes"

# suffix for generated .iso files
OUTPUT_SUFFIX="-revolutionary-ui"

# folder suffix for the package lists to use
PACKAGE_LISTS_SUFFIX="maxregneros-installer"
